name: Release & Homebrew Update

on:
  push:
    tags:
      - "v*" # Trigger workflow on new version tags (e.g., v1.0.0)

permissions:
  contents: write
env:
  GH_TOKEN: ${{ github.token }} # for release
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Get Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Binaries for macOS & Linux
        run: |
          make clean
          make build
      - name: Compute SHA256 Hashes
        run: |
          sha256sum bin/nr-linux-amd64 | awk '{ print $1 }' > sha256_linux_amd64.txt
          sha256sum bin/nr-linux-arm64 | awk '{ print $1 }' > sha256_linux_arm64.txt
          sha256sum bin/nr-darwin-amd64 | awk '{ print $1 }' > sha256_darwin_amd64.txt
          sha256sum bin/nr-darwin-arm64 | awk '{ print $1 }' > sha256_darwin_arm64.txt

          echo "SHA256_LINUX_AMD64=$(cat sha256_linux_amd64.txt)" >> $GITHUB_ENV
          echo "SHA256_LINUX_ARM64=$(cat sha256_linux_arm64.txt)" >> $GITHUB_ENV
          echo "SHA256_DARWIN_AMD64=$(cat sha256_darwin_amd64.txt)" >> $GITHUB_ENV
          echo "SHA256_DARWIN_ARM64=$(cat sha256_darwin_arm64.txt)" >> $GITHUB_ENV

      - name: Create GitHub Release with `gh`
        run: |
          gh release create "${{ env.VERSION }}" \
            bin/nr-linux-amd64 bin/nr-linux-arm64 \
            bin/nr-darwin-amd64 bin/nr-darwin-arm64 \
            --title "Release ${{ env.VERSION }}" \
            --notes "Automated release of ${{ env.VERSION }}"

      - name: Checkout Homebrew Tap Repository
        uses: actions/checkout@v4
        with:
          repository: silesky/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

      - name: Update Homebrew Formula
        run: |
          cat <<EOF > Formula/node-run.rb
          class NodeRun < Formula
            desc "Node-run (nr) - Your task runner"
            homepage "https://github.com/silesky/node-run"
            version "${{ env.VERSION }}"

            if OS.mac?
              if Hardware::CPU.intel?
                url "https://github.com/silesky/node-run/releases/download/${{ env.VERSION }}/nr-darwin-amd64"
                sha256 "${{ env.SHA256_DARWIN_AMD64 }}"
              else
                url "https://github.com/silesky/node-run/releases/download/${{ env.VERSION }}/nr-darwin-arm64"
                sha256 "${{ env.SHA256_DARWIN_ARM64 }}"
              end
            else
              if Hardware::CPU.intel?
                url "https://github.com/silesky/node-run/releases/download/${{ env.VERSION }}/nr-linux-amd64"
                sha256 "${{ env.SHA256_LINUX_AMD64 }}"
              else
                url "https://github.com/silesky/node-run/releases/download/${{ env.VERSION }}/nr-linux-arm64"
                sha256 "${{ env.SHA256_LINUX_ARM64 }}"
              end
            end

            license "MIT"

            def install
              bin.install "nr-darwin-#{Hardware::CPU.arch}" => "nr"
              chmod "+x", bin/"nr"
            end

            test do
              system "#{bin}/nr", "--help"
            end
          end
          EOF

      - name: Commit and Push Homebrew Formula Update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/node-run.rb
          git commit -m "Update node-run formula to ${{ env.VERSION }}"
          git push origin main
